# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        blog/:title

# Setup
title:            Marina orgánica
tagline:          'Biopoder en manos del agricultor'
description:      'En Marina orgánica producimos abonos y biofertilizantes buenos para la tierra, las personas y el bolsillo del agricultor.'
url:              http://hub.esclap.es/
baseurl:          '/marinaorganica'
paginate:         5

author:
  name:           'Eduardo Esclapes'
  url:            https://twitter.com/esclapes

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/esclapes/marinaorganica
