# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Marina orgánica
tagline:          'Biopoder en manos del agricultor'
description:      '.'
url:              http://hub.esclap.es
baseurl:          '/marinaorganica'
paginate:         5

author:
  name:           'Eduardo Esclapes'
  url:            https://twitter.com/esclapes

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/esclapes/marinaorganica
