# Dependencies
markdown:         redcarpet
highlighter:      highlighter

# Permalinks
permalink:        blog/:title

# Setup
title:            Marina orgánica
tagline:          'Biopoder en manos del agricultor'
description:      'En Marina orgánica producimos abonos y biofertilizantes buenos para la tierra, las personas y el bolsillo del agricultor.'
url:              http://www.marinaorganica.es/
baseurl:          ''
paginate:         5

collections:
  productos:
    output:       true
    layout:       page

author:
  name:           'Eduardo Esclapes'
  url:            https://twitter.com/esclapes

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/esclapes/marinaorganica
